_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 1
                - 5
            "12": 0.19.1
            "13": linux-x86_64
base_ex_num:
    value: "014"
batch_size:
    value: 8
cooling_rate:
    value: 0.9999
end_temperature:
    value: 0.001
iteration:
    value: 100
neighbor_types:
    value:
        - swap
        - insert
        - segment_insert
path:
    value: ../model
qid:
    value: 0
restart:
    value: true
restart_file_path:
    value: ../input/current_text.csv
save_interval:
    value: 10
seed:
    value: 42
start_temperature:
    value: 0.1
